baseURL = "https://1c-devops-jr.kropachev.digital/"
languageCode = "ru-ru"
title = "1C DevOps JR"
theme = "hugo-theme-stack"

[params]
  toc = true

[params.homepage]
  image = "https://github.com/kropachev.png"

[[menu.main]]
  name = "Документация"
  url = "/"
  weight = 1
