name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.8'
          extended: true

      - name: Debug list docs/ files
        run: |
          echo "===[ docs/ contents ]==="
          ls -la docs/ || echo "docs/ not found"

      - name: Concatenate all docs to p/wiki.md
        run: |
          echo "===[ Creating hugo-site/content/p/wiki.md ]==="
          mkdir -p hugo-site/content
          echo "---" > hugo-site/content/p/wiki.md
          echo 'title: "1C DevOps JR — Документация"' >> hugo-site/content/p/wiki.md
          echo "toc: true" >> hugo-site/content/p/wiki.md
          echo "---" >> hugo-site/content/p/wiki.md
          echo "" >> hugo-site/content/p/wiki.md

          for file in docs/*.md; do
            echo "Appending: $file"
            echo "<!-- ========== $file ========== -->" >> hugo-site/content/p/wiki.md
            echo "" >> hugo-site/content/p/wiki.md
            cat "$file" >> hugo-site/content/p/wiki.md
            echo "" >> hugo-site/content/p/wiki.md
            echo "" >> hugo-site/content/p/wiki.md
          done

          echo "===[ Preview of p/wiki.md ]==="
          head -n 30 hugo-site/content/p/wiki.md || echo "File not found"

      - name: Copy images
        run: |
          mkdir -p hugo-site/static/images
          cp -r docs/images/* hugo-site/static/images/ || echo "No images found"

      - name: Build site
        run: hugo --source hugo-site --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hugo-site/public
