name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.8'
          extended: true

      - name: Debug list docs files
        run: |
          echo "===[ docs/ contents ]==="
          ls -la docs/ || echo "docs/ not found"

      - name: Concatenate all docs to _index.md
        run: |
          echo "===[ Concatenating files... ]==="
          mkdir -p hugo-site/content/docs
          cat <<EOF > hugo-site/content/docs/_index.md
---
title: "1C DevOps JR — Документация"
---

EOF

          for f in docs/*.md; do
            echo "Appending: $f"
            echo "" >> hugo-site/content/docs/_index.md
            echo "<!-- ========== $f ========== -->" >> hugo-site/content/docs/_index.md
            cat "$f" >> hugo-site/content/docs/_index.md
            echo "" >> hugo-site/content/docs/_index.md
          done

          echo "===[ Preview of _index.md ]==="
          head -n 30 hugo-site/content/docs/_index.md || echo "File not found"

      - name: Build site
        run: hugo --source hugo-site --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo-site/public
  