name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.8'
          extended: true

      - name: Debug: list docs/ files
        run: |
          echo "===[ docs/ contents ]==="
          ls -la docs/ || echo "docs/ not found"

      - name: Concatenate all docs to _index.md
        run: |
          echo "===[ Creating hugo-site/content/_index.md ]==="
          mkdir -p hugo-site/content

          cat <<EOF > hugo-site/content/_index.md
---
title: "1C DevOps JR — Документация"
toc: true
---

EOF

          for file in $(find docs -type f -name "*.md" | sort); do
            echo "Appending: $file"
            echo -e "\n\n<!-- ========== $file ========== -->\n" >> hugo-site/content/_index.md
            cat "$file" >> hugo-site/content/_index.md
          done

      - name: Preview _index.md
        run: |
          echo "===[ Preview of _index.md ]==="
          head -n 30 hugo-site/content/_index.md || echo "File not found"

      - name: Build site
        run: hugo --source hugo-site --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hugo-site/public
