name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.8'
          extended: true

      - name: Concatenate all docs to _index.md
        run: |
          mkdir -p hugo-site/content
          echo '---' > hugo-site/content/_index.md
          echo 'title: "1C DevOps JR — Документация"' >> hugo-site/content/_index.md
          echo '---' >> hugo-site/content/_index.md
          echo '' >> hugo-site/content/_index.md

          find docs -maxdepth 1 -type f -name "*.md" | sort | while read file; do
            echo -e "\n\n<!-- ========== $file ========== -->\n\n" >> hugo-site/content/_index.md
            cat "$file" >> hugo-site/content/_index.md
          done

      - name: Build site
        run: hugo --source hugo-site --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hugo-site/public
